
version: '3.8'

services:

  meeting_application:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: meetingapplication
    depends_on:
      - redis_server
      - mysql_server
      - nginx
    ports:
      - "8080:8080"
    restart: always
    links:
      - mysql_server
    networks:
      - appnet


  redis_server:
    image: "docker.io/redis"
    container_name: redisserver
    restart: always
    ports:
    - 6379:6379
    networks:
      - appnet

  mysql_server:
    container_name: mysqlserver
    build:
      context: ./
      dockerfile: DockerfileSql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    networks:
      - appnet
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: DockerfileNginx
    volumes:
     -  /ngxin/conf.d:/etc/nginx/conf.d
     -  /ngxin/log:/var/log/nginx
     -  /ngxin//www:/var/www
     -  /etc/letsencrypt:/etc/letsencrypt

    ports:
      - 80:80
      - 443:443
    networks:
      - appnet

networks:
  appnet:
    driver: bridge