server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: false
        domain: wukaka.com
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/meeting2?serverTimezone=UTC
    password: root
    username: root
    hikari:
      max-lifetime: 1000000
  redis:
    database: 1 #索引
    host: 127.0.0.1
    port: 6379
#    password: root #修改成对应自己的redis密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接


tenlent:
  keys:
    SecretId:
    SecretKey:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com.hqgml.sign.mapper: debug


