server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/meeting2?serverTimezone=UTC
    password: root
    username: root
    hikari:
      max-lifetime: 1000000

tenlent:
  keys:
    SecretId: AKIDsZ5NYYlQ4X3Rdntq5Nh0CD7ED9xfYk1E
    SecretKey: 2vstqNktrWyEJDwVv8Ayd5LOVP7VijW8
