server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: false
        domain: wukaka.com

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/meeting2?&serverTimezone=GMT%2b8
    password: root
    username: root

  thymeleaf:
      check-template-location: false


  redis:
    database: 0 #索引
    host: 127.0.0.1
    port: 6379
    #    password: root #修改成对应自己的redis密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接

mybatis:
  type-aliases-package: com.hqgml.sign.pojo

tenlent:
  keys:
    SecretId: AKIDsZ5NYYlQ4X3Rdntq5Nh0CD7ED9xfYk1E
    SecretKey: 2vstqNktrWyEJDwVv8Ayd5LOVP7VijW8
  sms:

    appId: 1400401687
    appKey: b6f6fa209ba35122f5f3986e7fa827cf
#    签名
    sign: hqgml
#      通知全体
    sendAllTemplateId: 667078
#      通知单个
    sendOneTemplateId: 667080

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#    com.hqgml.sign.mapper: debug

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  tracker-list: # tracker地址：你的服务器地址+端口（默认是22122）
  - 49.232.54.164 :22122


hqgml:
  jwt:
    secret: dqdq@token(Auth}*^31)&hwwww% # 登录校验的密钥
    pubKeyPath: E:\jwtdemo\rsa.pub # 公钥地址
    priKeyPath: E:\jwtdemo\rsa.pri # 私钥地址
    expire: 130 #过期时间,单位分钟
    cookieName: auth
    tokenName: Authorization
    preToken : Bearer

  redis:
    tokenPre : Refresh_KEY-
    redisCache: 43200 #redis缓存token的过期时间 单位分钟 30天*
    disparity: 2880 #多少时间内没有登录刷新token失效 单位分钟