server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: false
        domain: wukaka.com

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/meeting2?serverTimezone=UTC
    password: root
    username: root

  redis:
    database: 0 #索引
    host: 127.0.0.1
    port: 6379
#    password: root #修改成对应自己的redis密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接


tenlent:
  keys:
    SecretId: AKIDsZ5NYYlQ4X3Rdntq5Nh0CD7ED9xfYk1E
    SecretKey: 2vstqNktrWyEJDwVv8Ayd5LOVP7VijW8


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#    com.hqgml.sign.mapper: debug

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
  - 49.232.54.164 :22122
