
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://49.232.54.164:3306/meeting?&serverTimezone=GMT%2b8
    username: meeting
    password: NDrBaHYdhk4ZbL7t
    hikari:
      connection-timeout: 100000
  thymeleaf:
      check-template-location: false

  redis:
    database: 0 #索引
    host: 127.0.0.1
    port: 6379
    #    password: root #修改成对应自己的redis密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接




#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#    com.hqgml.sign.mapper: debug
