


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysqlserver:3306/meeting?&serverTimezone=GMT%2b8
    username: root
    password: root
    hikari:
      connection-timeout: 100000
  thymeleaf:
      check-template-location: false

  redis:
    database: 0 #索引
    host: redisserver
    port: 6379
    #    password: root #修改成对应自己的redis密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接



tenlent:
#  所处地域
  region: ap-beijing
  keys:
    SecretId: AKIDsZ5NYYlQ4X3Rdntq5Nh0CD7ED9xfYk1E
    SecretKey: 2vstqNktrWyEJDwVv8Ayd5LOVP7VijW8
  cos:
    bucketName: faces-1259231187
  sms:
    appId: 1400401687
    appKey: b6f6fa209ba35122f5f3986e7fa827cf
#    签名
    sign: hqgml
#      通知全体
    sendAllTemplateId: 667078
#      通知单个
    sendOneTemplateId: 667080

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#    com.hqgml.sign.mapper: debug

